### PR TITLE
Add elements styling and grayscale heat map

### PR DESCRIPTION
**Pull request by flpfar**
This branch contains the following parts that compose the project:

- Every HTML container that evolves the items
- Elements positioning inside grid and flex
- All elements with grayscale backgrounds
- Every heat point based on four shades of gray
- Appropriate readme file

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @flpfar and  @ezeilo-su 
### Good job for the work done so far :clap: However, you have an issue to solve before your project could be approved.
- Divide, your columns equally, for example if 3 columns make them 3 and equal. Implement this where necessary
3 columnn equally
### Make this change and resubmit for another code review. Good luck.
- Happy coding!

**Comment by flpfar** [comment]
> Hello @flpfar and @ezeilo-su
> 
> ### Good job for the work done so far  However, you have an issue to solve before your project could be approved.
> * Divide, your columns equally, for example if 3 columns make them 3 and equal. Implement this where necessary
>   3 columnn equally
> 
> ### Make this change and resubmit for another code review. Good luck.
> * Happy coding!

Thank you for reviewing our code, rOluochKe!
We did this way of griding because it looks like the original website. Have a look at the following image (it is the original content and, in red, is the grid we've implemented):

example

Hope you can re-evaluate our project considering this point. If you don't agree, please let us know and we can implement it the way you said.

Best regards

**Comment by rOluochKe** [comment]
> > Hello @flpfar and @ezeilo-su
> > ### Good job for the work done so far  However, you have an issue to solve before your project could be approved.
> > 
> > * Divide, your columns equally, for example if 3 columns make them 3 and equal. Implement this where necessary
> >   3 columnn equally
> > 
> > ### Make this change and resubmit for another code review. Good luck.
> > 
> > * Happy coding!
> 
> Thank you for reviewing our code, rOluochKe!
> We did this way of griding because it looks like the original website. Have a look at the following image (it is the original content and, in red, is the grid we've implemented):
> 
> example
> 
> Hope you can re-evaluate our project considering this point. If you don't agree, please let us know and we can implement it the way you said.
> 
> Best regards

Sorry, that was a mistake. They look good now. You can resubmit for another review

**Review by rOluochKe — APPROVED** [review]
Hello @flpfar and @ezeilo-su 
### Well done, your project looks good and passes the requirements. I, therefore, approve of it. Congratulations :boom: :100:
### You can merge and submit a project completion form from your dashboard. Good luck with the next project.
- Happy coding!

**Pull request merged**
